### ISSUE TITLE
语音识别测试集

### ISSUE THREAD

**Issue by PaParaZz1** [bingduoduo1/backend#1]
三种类型
- 文本编辑器命令（如复制，粘贴，删除）
- python关键字 （先针对系统内置常用关键字）
- shell命令 （常用shell命令）
要求
- 优先覆盖英文输入（中文可选）
- 文字版 + 语音版

**Comment by binggge** [comment]
@PaParaZz1  https://github.com/bingduoduo1/public_doc/tree/master/sound%20testset
已完成 python 和shell部分的测试集构造

**Comment by PaParaZz1** [comment]
@sephyli 在文本编辑器设计时，请补充关于文本编辑器的简单测试集，格式参考@binggge的提交，提交在`public_doc`仓库
