### ISSUE TITLE
测试问题：语音识别到显示的逻辑问题

### ISSUE THREAD

**Issue by Melina-Zh** [bingduoduo1/backend#21]
**Feature description**
目前的实现逻辑就是根据识别到的串去字典中匹配，如果匹配不到就不输出。但是举一个简单的例子：用户输入一个变量名，这个变量名大概率下我们的字典中不存在。我们虽然加了每一个字母的字典，但是用户也不会一个字符一个字符输入自己的变量名。这个地方或许可以做出改进

**Reference implementation**
再termux和文本编辑器中均存在这个问题，是否可以再加入一个逻辑，可以更灵活实现这一部分的功能

**Comment by butub1** [comment]
done
