### ISSUE TITLE
史诗级bug(fixed)

### ISSUE THREAD

**Issue by butub1** [bingduoduo1/backend#22]
应用商店上架需要改变applicationID, termux已经使用com.termux上线，通常applicationＩＤ是和 app解耦合的，改变applicationID不会影响app的正常运行．所以我们改成了com.bingduoduo
---
但是发现termux-app中termux-service中的FILE_PATH字段硬编码成 "/data/data/com.termux/files";
也就是应用的私有缓存目录，这个目录android中对于用户和开发者都是不可见的．termux做的一件事是把启动所需的包缓存到这个目录，然后使用系统函数链接到linux内核环境中去，就能够模拟出一个shell环境，于是我们把这个路径也改成＂/data/data/com.bingduoudo/files＂
---
但是发现bug,正常编译，初始化时对话框一直installing...，表示正在安装bootstrap的包，logcat显示出下载成功，但是链接的时候出错．这时这个bug已经de了有两天，　原因在于termux自己维护的源的包，在编译的时候有硬编码的字段$PREFIX,对应包名　＂com.termux＂, 于是我们需要自己重新编译这些包，　自己维护一个源，　https://github.com/termux/termux-app/issues/1059 , 
---
按照issue中的方法，安装docker, 编译需要的包，生成Ｐackages, 上传到服务器，用脚本生成boostraps-arm.zip，　在传到github上，修改termux-app中的termuxInstaller中的url字段为github上对应的网址．
---
下载运行，发现包可以下载，　链接也正常，启动的shell和termux本身的也一样，但是运行时，手机显示CANNOT LINK EXECUTABLE, 发现在docker中重新编译所有需要的包的时候，　有一个字段TERMUX_PKG_API_LEVEL设置成了最高的28, 所以在android api 28的手机上能够运行，　而在androidapi22上的测试机就不能用
---
所以我们需要编译TERMUX_PKG_API_LEVEL 21的包，这里还有一些包的依赖关系，我们最终编了个24的，　在小米７上可以run，
---

**Comment by CMingTseng** [comment]
你好

可以請問一下步驟嗎？

這個 『生成Ｐackages, 上传到服务器』

有詳細的做法嗎？

謝謝

**Comment by butub1** [comment]
> 你好
> 
> 可以請問一下步驟嗎？
> 
> 這個 『生成Ｐackages, 上传到服务器』
> 
> 有詳細的做法嗎？
> 
> 謝謝

refer to https://www.cnblogs.com/bingduoduo/p/10918759.html

**Comment by CMingTseng** [comment]
> > 你好
> > 可以請問一下步驟嗎？
> > 這個 『生成Ｐackages, 上传到服务器』
> > 有詳細的做法嗎？
> > 謝謝
> 
> refer to https://www.cnblogs.com/bingduoduo/p/10918759.html
你好

我有找到這篇

可是目前有幾個地方卡住

因此來此發問

1.   编译好bootstrap所需的包之后，生成Package 列表:

dpkg-scanpackages ./  /dev/null | Packages # ./ 为软件包所在目录

這邊|好像要 >

因為如果用 dpkg-scanpackages ./  /dev/null | Packages  

會出現

builder@971a829b40f9:~/termux-packages/debs$ dpkg-scanpackages ./  /dev/null | Packages
bash: Packages: command not found

2.  我同樣參考 1059 -- https://github.com/termux/termux-app/issues/1059#issuecomment-471497714

我的理解比較差

我目前先clone  https://github.com/termux/termux-packages

進入docker後  執行 ./build-all.sh  產生deb後

目前要怎麼傳送到  APT repository ?

我看他 scripts內有 package_uploader.sh

大約要修改 BINTRAY 的哪些東西？

有參考的GPG教學？

看不太懂 BINTRAY_GPG_SUBJECT需要填入哪些資料？

如果要用  private 的  APT repository有推薦的docker 可用？

然後

把deb推到  APT repository之後是否接著用

https://github.com/termux/termux-packaging

這個來包出bootstraps ?

有辦法不用 apt 直接讀取local deb製作嗎？

謝謝

**Comment by butub1** [comment]
1.确实需要用>来重定向，博客写错了。
2.
①所谓的apt repo，就是你放*.deb的服务器，所以你首先需要有一个服务器，用apache或者nginx来搭建一个文件服务，这个[博客](https://www.cnblogs.com/bingduoduo/p/10917554.html)里也有。有服务，并且配置好服务后，直接scp传到服务器对应目录就行了

②那个package_uploader.sh应该是用来上传到temux自己的服务器上的吧，不确定，我没看。

③有参考GPG教程，但是这个工具用来加密deb包的，我们实际上并没有使用，网上步骤都差不多。

④你用私有的APT repo干嘛，(1) 想在本地生成不用下载？其实是可以的，编译完包之后，[打包](https://github.com/termux/termux-packaging)这些包成一个zip和termux-app项目放在一起，然后修改temux-app的源码，注释掉他们下载包的地方，改成从本地资源获取就行了。(2)想做一个本地的apt源，像很多博客做的那样？没有必要，因为包都在本地编译好了可以直接获取，并且只能在android端使用。

⑤打包仍然用[packaging](https://github.com/termux/termux-packaging)脚本，注意修改脚本里面的变量，因为要用到自己的app，里面的路径是不同的。

⑥local deb参考④

> PS: 问题多的话，建议多加一些序号，回答起来方便。

**Comment by CMingTseng** [comment]
> 1.确实需要用>来重定向，博客写错了。
> 2.
> ①所谓的apt repo，就是你放*.deb的服务器，所以你首先需要有一个服务器，用apache或者nginx来搭建一个文件服务，这个[博客](https://www.cnblogs.com/bingduoduo/p/10917554.html)里也有。有服务，并且配置好服务后，直接scp传到服务器对应目录就行了
> 
> ②那个package_uploader.sh应该是用来上传到temux自己的服务器上的吧，不确定，我没看。
> 
> ③有参考GPG教程，但是这个工具用来加密deb包的，我们实际上并没有使用，网上步骤都差不多。
> 
> ④你用私有的APT repo干嘛，(1) 想在本地生成不用下载？其实是可以的，编译完包之后，[打包](https://github.com/termux/termux-packaging)这些包成一个zip和termux-app项目放在一起，然后修改temux-app的源码，注释掉他们下载包的地方，改成从本地资源获取就行了。(2)想做一个本地的apt源，像很多博客做的那样？没有必要，因为包都在本地编译好了可以直接获取，并且只能在android端使用。
> 
> ⑤打包仍然用[packaging](https://github.com/termux/termux-packaging)脚本，注意修改脚本里面的变量，因为要用到自己的app，里面的路径是不同的。
> 
> ⑥local deb参考④
> 
> > PS: 问题多的话，建议多加一些序号，回答起来方便。

感謝您的解惑

我目前

1. 目前需要產生自己的 bootstraps.zip  因為我們自己的也算改過applicationid （安裝路徑不在data/data之下） 需要一個基礎的bootstraps驗證

2.  最終應用算是簡單  只要golang/python的編譯/執行環境  所以需要的deb檔案是知道的  之前改了termux-app的class有拿到shell  但是要用 dpkg -i  xxx.deb的時候就會遭遇  apt/dpkg的database路徑錯誤
(顯示  data/data/com/termux/....)

3. [编译完包之后，打包这些包成一个zip和termux-app项目放在一起]  請問這邊怎麼修改？大約哪些部分？因為需要產生一個 bootstraps.zip 

PS. 請問有IM （wechat/qq/TG/...）可以直接交談嗎？ 看你們好像很有心得  謝謝

**Comment by butub1** [comment]
termux的项目是这个样子的，通读源码的话就会知道，它是使用JNI在本地开进程来产生shell的，本地的shell环境是需要由bootstrap.zip来提供的，这个bootstrap.zip是至少要包含sh,apt等其他必要的包的，在app安装后的第一次启动初始化整个环境，之后如果需要别的包，就可以用apt-get install来安装了。原本的termux是从服务器下载bootstrap.zip后解压缩自动安装环境的，所以，bootstrap.zip是必须的，且所有包的路径都必须改。
１．什么叫基础的bootstrap验证?
２．看起来你似乎吧deb包放在本地用dpkg -i安装，我不知道dpkg在安装的时候是否需要什么验证信息。我们当初的实现方式是修改apt的源配置到自己的服务器目录，然后用apt-get update档案信息，再安装。提示data/data/com/termux...可能编译包的时候的路径错，或者dpkg的问题，不清楚。
３．所以你们还不会打包bootstraps.zip？那你们还卡在很开始的地方啊..不是有打包的脚本吗，用shell脚本就可以了，产生zip后，放在项目资源目录app/src/main/res/raw/bootstrapaarch64.zip，然后在com/termux/app/TermuxInstaller.java中修改为：
```
 InputStream bootInput = activity.getResources().openRawResource(R.raw.bootstrapaarch64);
                    try (ZipInputStream zipInput = new ZipInputStream(bootInput)) {
```
就可以了。
> PS.　可以加微信:butub666

**Comment by CMingTseng** [comment]
> termux的项目是这个样子的，通读源码的话就会知道，它是使用JNI在本地开进程来产生shell的，本地的shell环境是需要由bootstrap.zip来提供的，这个bootstrap.zip是至少要包含sh,apt等其他必要的包的，在app安装后的第一次启动初始化整个环境，之后如果需要别的包，就可以用apt-get install来安装了。原本的termux是从服务器下载bootstrap.zip后解压缩自动安装环境的，所以，bootstrap.zip是必须的，且所有包的路径都必须改。
> １．什么叫基础的bootstrap验证?
> ２．看起来你似乎吧deb包放在本地用dpkg -i安装，我不知道dpkg在安装的时候是否需要什么验证信息。我们当初的实现方式是修改apt的源配置到自己的服务器目录，然后用apt-get update档案信息，再安装。提示data/data/com/termux...可能编译包的时候的路径错，或者dpkg的问题，不清楚。
> ３．所以你们还不会打包bootstraps.zip？那你们还卡在很开始的地方啊..不是有打包的脚本吗，用shell脚本就可以了，产生zip后，放在项目资源目录app/src/main/res/raw/bootstrapaarch64.zip，然后在com/termux/app/TermuxInstaller.java中修改为：
> 
> ```
>  InputStream bootInput = activity.getResources().openRawResource(R.raw.bootstrapaarch64);
>                     try (ZipInputStream zipInput = new ZipInputStream(bootInput)) {
> ```
> 
> 就可以了。
> 
> > PS.　可以加微信:butub666

1. 抱歉描述得不夠清楚  我知道要改 路徑符合 applicationid與TermuxInstaller  （之前參考 1059）
只是我做了一點修改在BackgroundJob這邊的getSetupProcessArgs這邊
強制給予interpreter = Config.PREFIX_PATH + "/bin/sh";
然後我在沒有更改FILES_PATH 的狀況下（維持/data/data/com.termux/files）
成功取得app的shell (/bin/sh) 

2. 上面說的InputStream bootInput = activity.getResources().openRawResource(R.raw.bootstrapaarch64)

我就是這樣使用（先使用termux的bootstrap 與 deb）然後搭配上面的修改

我是可以拿到shell執行dpkg  但是因為 dpkg的安裝好像有個參照資料庫

所以會提示  /data/data/com.termux不存在


3. 如果 沒改 applicationId 的話 local bootstrap可以安裝 然後可以安裝local  deb (使用 dpkg -i)

**Comment by qianxin12568** [comment]
> ## 应用商店上架需要改变applicationID, termux已经使用com.termux上线，通常applicationＩＤ是和 app解耦合的，改变applicationID不会影响app的正常运行．所以我们改成了com.bingduoduo
> ## 但是发现termux-app中termux-service中的FILE_PATH字段硬编码成 "/data/data/com.termux/files";
> 也就是应用的私有缓存目录，这个目录android中对于用户和开发者都是不可见的．termux做的一件事是把启动所需的包缓存到这个目录，然后使用系统函数链接到linux内核环境中去，就能够模拟出一个shell环境，于是我们把这个路径也改成＂/data/data/com.bingduoudo/files＂
> ## 但是发现bug,正常编译，初始化时对话框一直installing...，表示正在安装bootstrap的包，logcat显示出下载成功，但是链接的时候出错．这时这个bug已经de了有两天，　原因在于termux自己维护的源的包，在编译的时候有硬编码的字段$PREFIX,对应包名　＂com.termux＂, 于是我们需要自己重新编译这些包，　自己维护一个源，　[termux/termux-app#1059](https://github.com/termux/termux-app/issues/1059) ,
> ## 按照issue中的方法，安装docker, 编译需要的包，生成Ｐackages, 上传到服务器，用脚本生成boostraps-arm.zip，　在传到github上，修改termux-app中的termuxInstaller中的url字段为github上对应的网址．
> ## 下载运行，发现包可以下载，　链接也正常，启动的shell和termux本身的也一样，但是运行时，手机显示CANNOT LINK EXECUTABLE, 发现在docker中重新编译所有需要的包的时候，　有一个字段TERMUX_PKG_API_LEVEL设置成了最高的28, 所以在android api 28的手机上能够运行，　而在androidapi22上的测试机就不能用
> ## 所以我们需要编译TERMUX_PKG_API_LEVEL 21的包，这里还有一些包的依赖关系，我们最终编了个24的，　在小米７上可以run，

你好,我想修改这个application id,总体能否理解大概如下理解:
1. 首先,按docker的方式打包bootstrap,并且上传到某个站点.
2. 回到termux-app,修改app下build.gradle内的默认配置的application id为我想要的值.
3. 到src下的termuxService下修改FILES_PATH为/data/data/{new.applicationid}/files
4. 修改build.grade内下载上传好的bootstrap包的地址和相关哈希验证的逻辑代码
5. 构建apk

这个时候,除了不能使用官方的apt源软件,其他的都正常了对吧?
多谢解答.
