### ISSUE TITLE
shell和编辑器的连接

### ISSUE THREAD

**Issue by KarCute** [bingduoduo1/backend#24]
目前我们界面仍然沿用的是termux的界面
需要将已经完成的正常运行的**后端shell**与改自MarkdownEditors的**前端编辑器**完成连接，基本达到此项目在一开始预定的效果。

@binggge 
@sephyli 
@PaParaZz1

**Comment by butub1** [comment]
因为前端需要，我合幷了一下，开了一个新的仓库
https://github.com/bingduoduo1/bingduoduo

能build能run,功能还没写，目前包名还是com.termux,我怕一次修改太多不同的部分造成严重复杂的错误．之后会修改成com.bingduoduo

**Comment by butub1** [comment]
已经连接好了，
尝试用ViewPager切换，以及用Activity的Gesture识别，都不是很方便做
所以加两个Button基本连接上
