### ISSUE TITLE
编辑器功能完善：添加使用说明界面

### ISSUE THREAD

**Issue by KarCute** [bingduoduo1/backend#38]
仿照MarkdownEditors在编辑器中加上使用说明的界面
@sephyli

**Comment by sephyli** [comment]
使用说明界面已添加，顺便de了一个编辑器界面的BUG。在activity_main中，NavigationView必须位于最下方，才可以正确触发菜单点击事件。bingduoduo的切换界面按钮被加在了其下，导致菜单失效。

目前该按钮会直接打开bingduoduo项目的[README.md](https://github.com/bingduoduo1/bingduoduo/blob/master/README.md)，回头等PM拟合一份使用说明发布在github.io上，或者生成一个本地的html文件附在assets里，就可以获得一个合格的使用说明了
