### ISSUE TITLE
文本编辑器需求分析和简单设计

### ISSUE THREAD

**Issue by PaParaZz1** [bingduoduo1/backend#4]
需要完成本项目所需要的文本编辑器的需求分析，整理成文档，并完成初版设计报告

**Comment by PaParaZz1** [comment]
周三DDL

**Comment by sephyli** [comment]
已将初版文档push到public_doc上

**Comment by butub1** [comment]
> 已将初版文档push到public_doc上

恩，不如我们就先做编辑器的编辑模式，命令模式之后再想办法，语音的接口这周应该能定．

**Comment by PaParaZz1** [comment]
@sephyli 建议先做编辑的基本输入和删除，本周我会提供语音输入结果的基本接口，然后你可以推一个文本编辑器的demo
