### ISSUE TITLE
语音识别API调研和验证

### ISSUE THREAD

**Issue by PaParaZz1** [bingduoduo1/backend#5]
1.百度API
2.科大讯飞API
3.腾讯API
要求：跑通demo并封装简易接口，接口标准之后更新

**Comment by PaParaZz1** [comment]
@PaParaZz1 科大讯飞API部分

**Comment by PaParaZz1** [comment]
@Melina-Zh 百度API部分

**Comment by PaParaZz1** [comment]
腾讯API部分已由@butub1解决

**Comment by PaParaZz1** [comment]
科大讯飞部分已解决，准备提供语音识别API接口的简易文档

**Comment by PaParaZz1** [comment]
讯飞语音识别接口的简易文档已提交. [链接](https://github.com/bingduoduo1/public_doc/blob/master/%E7%A7%91%E5%A4%A7%E8%AE%AF%E9%A3%9E%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%ABdemo%E6%96%87%E6%A1%A3.md)

**Comment by Melina-Zh** [comment]
百度语音接口的简易文档已提交.[链接](https://github.com/bingduoduo1/public_doc/blob/master/%E7%99%BE%E5%BA%A6%E4%BA%91%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%ABdemo%E6%96%87%E6%A1%A3.md)
